# Generated by Django 4.2.8 on 2024-01-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('ocupation', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'Especialidad de los trabajadores',
            },
        ),
    ]
