# Generated by Django 4.2.8 on 2024-01-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_ocupation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'Ubicacion y Compania',
            },
        ),
    ]
