# Generated by Django 4.2.8 on 2024-01-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitales',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('capital', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'Paises y Capitales',
            },
        ),
    ]
