# Generated by Django 4.2.8 on 2024-01-05 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capitales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='capitales',
            table='PaisesyCapitales',
        ),
    ]
